#!/usr/bin/env -S python3 -u

import argparse
import semlogcompress

p = argparse.ArgumentParser(description="Semantic compression of log files.")
p.add_argument("files", metavar="FILE", type=str, nargs="+", help="Log file(s) to process; use '-' for stdin")
p.add_argument("-l", "--limit-lines", dest="limit_lines", type=int, help="Only process few lines")
p.add_argument("-v", "--verbose", dest="verbose", action="store_const", const=True, default=False, help="Turn on verbosity")
p.add_argument("-j", "--json-format", dest="json", action="store_const", const=True, default=False, help="JSON-formatted attribute stream")
args = p.parse_args()

for fn in args.files:
	msgs = semlogcompress.process(fn, args.verbose, args.limit_lines, args.json)
	retlist = semlogcompress.handle(msgs, args.verbose, args.json)
	semlogcompress.persist(retlist)
